// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xddr_hls_test.h"

extern XDdr_hls_test_Config XDdr_hls_test_ConfigTable[];

XDdr_hls_test_Config *XDdr_hls_test_LookupConfig(u16 DeviceId) {
	XDdr_hls_test_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XDDR_HLS_TEST_NUM_INSTANCES; Index++) {
		if (XDdr_hls_test_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XDdr_hls_test_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XDdr_hls_test_Initialize(XDdr_hls_test *InstancePtr, u16 DeviceId) {
	XDdr_hls_test_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XDdr_hls_test_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XDdr_hls_test_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

