// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _ddr_hls_test_HH_
#define _ddr_hls_test_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "ddr_hls_test_addrbkb.h"
#include "ddr_hls_test_BUS_A_s_axi.h"
#include "ddr_hls_test_gmem_m_axi.h"

namespace ap_rtl {

template<unsigned int C_M_AXI_GMEM_ADDR_WIDTH = 32,
         unsigned int C_M_AXI_GMEM_ID_WIDTH = 1,
         unsigned int C_M_AXI_GMEM_AWUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM_DATA_WIDTH = 64,
         unsigned int C_M_AXI_GMEM_WUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM_ARUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM_RUSER_WIDTH = 1,
         unsigned int C_M_AXI_GMEM_BUSER_WIDTH = 1,
         unsigned int C_S_AXI_BUS_A_ADDR_WIDTH = 6,
         unsigned int C_S_AXI_BUS_A_DATA_WIDTH = 32>
struct ddr_hls_test : public sc_module {
    // Port declarations 65
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_out< sc_logic > m_axi_gmem_AWVALID;
    sc_in< sc_logic > m_axi_gmem_AWREADY;
    sc_out< sc_uint<C_M_AXI_GMEM_ADDR_WIDTH> > m_axi_gmem_AWADDR;
    sc_out< sc_uint<C_M_AXI_GMEM_ID_WIDTH> > m_axi_gmem_AWID;
    sc_out< sc_lv<8> > m_axi_gmem_AWLEN;
    sc_out< sc_lv<3> > m_axi_gmem_AWSIZE;
    sc_out< sc_lv<2> > m_axi_gmem_AWBURST;
    sc_out< sc_lv<2> > m_axi_gmem_AWLOCK;
    sc_out< sc_lv<4> > m_axi_gmem_AWCACHE;
    sc_out< sc_lv<3> > m_axi_gmem_AWPROT;
    sc_out< sc_lv<4> > m_axi_gmem_AWQOS;
    sc_out< sc_lv<4> > m_axi_gmem_AWREGION;
    sc_out< sc_uint<C_M_AXI_GMEM_AWUSER_WIDTH> > m_axi_gmem_AWUSER;
    sc_out< sc_logic > m_axi_gmem_WVALID;
    sc_in< sc_logic > m_axi_gmem_WREADY;
    sc_out< sc_uint<C_M_AXI_GMEM_DATA_WIDTH> > m_axi_gmem_WDATA;
    sc_out< sc_uint<C_M_AXI_GMEM_DATA_WIDTH/8> > m_axi_gmem_WSTRB;
    sc_out< sc_logic > m_axi_gmem_WLAST;
    sc_out< sc_uint<C_M_AXI_GMEM_ID_WIDTH> > m_axi_gmem_WID;
    sc_out< sc_uint<C_M_AXI_GMEM_WUSER_WIDTH> > m_axi_gmem_WUSER;
    sc_out< sc_logic > m_axi_gmem_ARVALID;
    sc_in< sc_logic > m_axi_gmem_ARREADY;
    sc_out< sc_uint<C_M_AXI_GMEM_ADDR_WIDTH> > m_axi_gmem_ARADDR;
    sc_out< sc_uint<C_M_AXI_GMEM_ID_WIDTH> > m_axi_gmem_ARID;
    sc_out< sc_lv<8> > m_axi_gmem_ARLEN;
    sc_out< sc_lv<3> > m_axi_gmem_ARSIZE;
    sc_out< sc_lv<2> > m_axi_gmem_ARBURST;
    sc_out< sc_lv<2> > m_axi_gmem_ARLOCK;
    sc_out< sc_lv<4> > m_axi_gmem_ARCACHE;
    sc_out< sc_lv<3> > m_axi_gmem_ARPROT;
    sc_out< sc_lv<4> > m_axi_gmem_ARQOS;
    sc_out< sc_lv<4> > m_axi_gmem_ARREGION;
    sc_out< sc_uint<C_M_AXI_GMEM_ARUSER_WIDTH> > m_axi_gmem_ARUSER;
    sc_in< sc_logic > m_axi_gmem_RVALID;
    sc_out< sc_logic > m_axi_gmem_RREADY;
    sc_in< sc_uint<C_M_AXI_GMEM_DATA_WIDTH> > m_axi_gmem_RDATA;
    sc_in< sc_logic > m_axi_gmem_RLAST;
    sc_in< sc_uint<C_M_AXI_GMEM_ID_WIDTH> > m_axi_gmem_RID;
    sc_in< sc_uint<C_M_AXI_GMEM_RUSER_WIDTH> > m_axi_gmem_RUSER;
    sc_in< sc_lv<2> > m_axi_gmem_RRESP;
    sc_in< sc_logic > m_axi_gmem_BVALID;
    sc_out< sc_logic > m_axi_gmem_BREADY;
    sc_in< sc_lv<2> > m_axi_gmem_BRESP;
    sc_in< sc_uint<C_M_AXI_GMEM_ID_WIDTH> > m_axi_gmem_BID;
    sc_in< sc_uint<C_M_AXI_GMEM_BUSER_WIDTH> > m_axi_gmem_BUSER;
    sc_in< sc_logic > s_axi_BUS_A_AWVALID;
    sc_out< sc_logic > s_axi_BUS_A_AWREADY;
    sc_in< sc_uint<C_S_AXI_BUS_A_ADDR_WIDTH> > s_axi_BUS_A_AWADDR;
    sc_in< sc_logic > s_axi_BUS_A_WVALID;
    sc_out< sc_logic > s_axi_BUS_A_WREADY;
    sc_in< sc_uint<C_S_AXI_BUS_A_DATA_WIDTH> > s_axi_BUS_A_WDATA;
    sc_in< sc_uint<C_S_AXI_BUS_A_DATA_WIDTH/8> > s_axi_BUS_A_WSTRB;
    sc_in< sc_logic > s_axi_BUS_A_ARVALID;
    sc_out< sc_logic > s_axi_BUS_A_ARREADY;
    sc_in< sc_uint<C_S_AXI_BUS_A_ADDR_WIDTH> > s_axi_BUS_A_ARADDR;
    sc_out< sc_logic > s_axi_BUS_A_RVALID;
    sc_in< sc_logic > s_axi_BUS_A_RREADY;
    sc_out< sc_uint<C_S_AXI_BUS_A_DATA_WIDTH> > s_axi_BUS_A_RDATA;
    sc_out< sc_lv<2> > s_axi_BUS_A_RRESP;
    sc_out< sc_logic > s_axi_BUS_A_BVALID;
    sc_in< sc_logic > s_axi_BUS_A_BREADY;
    sc_out< sc_lv<2> > s_axi_BUS_A_BRESP;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_logic > ap_var_for_const6;
    sc_signal< sc_lv<32> > ap_var_for_const2;
    sc_signal< sc_lv<1> > ap_var_for_const1;
    sc_signal< sc_lv<3> > ap_var_for_const3;
    sc_signal< sc_lv<2> > ap_var_for_const4;
    sc_signal< sc_lv<4> > ap_var_for_const5;
    sc_signal< sc_lv<8> > ap_var_for_const7;


    // Module declarations
    ddr_hls_test(sc_module_name name);
    SC_HAS_PROCESS(ddr_hls_test);

    ~ddr_hls_test();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    ddr_hls_test_addrbkb* addr_bram_U;
    ddr_hls_test_BUS_A_s_axi<C_S_AXI_BUS_A_ADDR_WIDTH,C_S_AXI_BUS_A_DATA_WIDTH>* ddr_hls_test_BUS_A_s_axi_U;
    ddr_hls_test_gmem_m_axi<0,64,32,5,1,1,4,4,C_M_AXI_GMEM_ID_WIDTH,C_M_AXI_GMEM_ADDR_WIDTH,C_M_AXI_GMEM_DATA_WIDTH,C_M_AXI_GMEM_AWUSER_WIDTH,C_M_AXI_GMEM_ARUSER_WIDTH,C_M_AXI_GMEM_WUSER_WIDTH,C_M_AXI_GMEM_RUSER_WIDTH,C_M_AXI_GMEM_BUSER_WIDTH,C_M_AXI_GMEM_USER_VALUE,C_M_AXI_GMEM_PROT_VALUE,C_M_AXI_GMEM_CACHE_VALUE>* ddr_hls_test_gmem_m_axi_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<23> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<32> > start_signal_i;
    sc_signal< sc_lv<32> > start_signal_o;
    sc_signal< sc_logic > start_signal_o_ap_vld;
    sc_signal< sc_lv<32> > hls_check;
    sc_signal< sc_logic > hls_check_ap_vld;
    sc_signal< sc_lv<32> > num;
    sc_signal< sc_lv<32> > saMaster;
    sc_signal< sc_lv<14> > addr_bram_address0;
    sc_signal< sc_logic > addr_bram_ce0;
    sc_signal< sc_lv<24> > addr_bram_q0;
    sc_signal< sc_logic > gmem_blk_n_AW;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_logic > gmem_blk_n_W;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_logic > gmem_blk_n_B;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_logic > gmem_blk_n_AR;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_logic > gmem_blk_n_R;
    sc_signal< sc_logic > ap_CS_fsm_state22;
    sc_signal< sc_logic > gmem_AWVALID;
    sc_signal< sc_logic > gmem_AWREADY;
    sc_signal< sc_lv<32> > gmem_AWADDR;
    sc_signal< sc_logic > gmem_WVALID;
    sc_signal< sc_logic > gmem_WREADY;
    sc_signal< sc_lv<64> > gmem_WDATA;
    sc_signal< sc_logic > gmem_ARVALID;
    sc_signal< sc_logic > gmem_ARREADY;
    sc_signal< sc_lv<32> > gmem_ARADDR;
    sc_signal< sc_logic > gmem_RVALID;
    sc_signal< sc_logic > gmem_RREADY;
    sc_signal< sc_lv<64> > gmem_RDATA;
    sc_signal< sc_logic > gmem_RLAST;
    sc_signal< sc_lv<1> > gmem_RID;
    sc_signal< sc_lv<1> > gmem_RUSER;
    sc_signal< sc_lv<2> > gmem_RRESP;
    sc_signal< sc_logic > gmem_BVALID;
    sc_signal< sc_logic > gmem_BREADY;
    sc_signal< sc_lv<2> > gmem_BRESP;
    sc_signal< sc_lv<1> > gmem_BID;
    sc_signal< sc_lv<1> > gmem_BUSER;
    sc_signal< sc_lv<30> > tmp_10_cast_fu_229_p1;
    sc_signal< sc_lv<30> > tmp_10_cast_reg_371;
    sc_signal< sc_lv<32> > run_cnt_reg_387;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > tmp_fu_233_p2;
    sc_signal< sc_lv<32> > j_cast_fu_244_p1;
    sc_signal< sc_lv<32> > j_cast_reg_392;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<31> > j_1_fu_253_p2;
    sc_signal< sc_lv<31> > j_1_reg_401;
    sc_signal< sc_lv<32> > i_1_cast2_fu_259_p1;
    sc_signal< sc_lv<32> > i_1_cast2_reg_409;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<14> > i_fu_269_p2;
    sc_signal< sc_lv<14> > i_reg_417;
    sc_signal< sc_lv<1> > exitcond1_fu_263_p2;
    sc_signal< sc_lv<32> > tmp_2_fu_280_p2;
    sc_signal< sc_lv<32> > tmp_2_reg_427;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<30> > saMaster2_sum_fu_288_p2;
    sc_signal< sc_lv<30> > saMaster2_sum_reg_432;
    sc_signal< sc_logic > ap_sig_ioackin_gmem_AWREADY;
    sc_signal< sc_lv<14> > i_3_fu_317_p2;
    sc_signal< sc_lv<14> > i_3_reg_446;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_lv<1> > exitcond_fu_311_p2;
    sc_signal< sc_lv<32> > tmp_s_fu_328_p2;
    sc_signal< sc_lv<32> > tmp_s_reg_456;
    sc_signal< sc_lv<30> > saMaster2_sum3_fu_337_p2;
    sc_signal< sc_lv<30> > saMaster2_sum3_reg_461;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_logic > ap_sig_ioackin_gmem_ARREADY;
    sc_signal< sc_lv<64> > gmem_addr_1_read_reg_472;
    sc_signal< sc_lv<31> > j_reg_183;
    sc_signal< sc_lv<14> > i_1_reg_194;
    sc_signal< sc_lv<1> > tmp_1_fu_248_p2;
    sc_signal< sc_lv<14> > i_2_reg_205;
    sc_signal< sc_logic > ap_CS_fsm_state23;
    sc_signal< sc_lv<64> > tmp_4_fu_275_p1;
    sc_signal< sc_lv<64> > tmp_8_fu_323_p1;
    sc_signal< sc_lv<64> > saMaster2_sum_cast_fu_293_p1;
    sc_signal< sc_lv<64> > saMaster2_sum3_cast_fu_342_p1;
    sc_signal< sc_logic > ap_reg_ioackin_gmem_AWREADY;
    sc_signal< sc_logic > ap_reg_ioackin_gmem_WREADY;
    sc_signal< sc_logic > ap_sig_ioackin_gmem_WREADY;
    sc_signal< sc_logic > ap_reg_ioackin_gmem_ARREADY;
    sc_signal< sc_lv<1> > res_check_fu_94;
    sc_signal< sc_lv<1> > res_check_1_fu_360_p2;
    sc_signal< sc_lv<1> > grp_load_fu_216_p1;
    sc_signal< sc_lv<29> > tmp_5_fu_219_p4;
    sc_signal< sc_lv<30> > tmp_5_cast_fu_284_p1;
    sc_signal< sc_lv<32> > i_2_cast1_fu_307_p1;
    sc_signal< sc_lv<30> > tmp_9_cast_fu_333_p1;
    sc_signal< sc_lv<64> > tmp_6_fu_352_p1;
    sc_signal< sc_lv<1> > tmp_7_fu_355_p2;
    sc_signal< sc_lv<23> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<23> ap_ST_fsm_state1;
    static const sc_lv<23> ap_ST_fsm_state2;
    static const sc_lv<23> ap_ST_fsm_state3;
    static const sc_lv<23> ap_ST_fsm_state4;
    static const sc_lv<23> ap_ST_fsm_state5;
    static const sc_lv<23> ap_ST_fsm_state6;
    static const sc_lv<23> ap_ST_fsm_state7;
    static const sc_lv<23> ap_ST_fsm_state8;
    static const sc_lv<23> ap_ST_fsm_state9;
    static const sc_lv<23> ap_ST_fsm_state10;
    static const sc_lv<23> ap_ST_fsm_state11;
    static const sc_lv<23> ap_ST_fsm_state12;
    static const sc_lv<23> ap_ST_fsm_state13;
    static const sc_lv<23> ap_ST_fsm_state14;
    static const sc_lv<23> ap_ST_fsm_state15;
    static const sc_lv<23> ap_ST_fsm_state16;
    static const sc_lv<23> ap_ST_fsm_state17;
    static const sc_lv<23> ap_ST_fsm_state18;
    static const sc_lv<23> ap_ST_fsm_state19;
    static const sc_lv<23> ap_ST_fsm_state20;
    static const sc_lv<23> ap_ST_fsm_state21;
    static const sc_lv<23> ap_ST_fsm_state22;
    static const sc_lv<23> ap_ST_fsm_state23;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_15;
    static const int C_S_AXI_DATA_WIDTH;
    static const int C_M_AXI_GMEM_USER_VALUE;
    static const int C_M_AXI_GMEM_PROT_VALUE;
    static const int C_M_AXI_GMEM_CACHE_VALUE;
    static const int C_M_AXI_DATA_WIDTH;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<31> ap_const_lv31_0;
    static const sc_lv<14> ap_const_lv14_0;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<32> ap_const_lv32_4D2;
    static const sc_lv<32> ap_const_lv32_10E1;
    static const sc_lv<32> ap_const_lv32_32F;
    static const sc_lv<32> ap_const_lv32_206;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_7CA;
    static const sc_lv<31> ap_const_lv31_1;
    static const sc_lv<14> ap_const_lv14_2800;
    static const sc_lv<14> ap_const_lv14_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const6();
    void thread_ap_var_for_const2();
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const3();
    void thread_ap_var_for_const4();
    void thread_ap_var_for_const5();
    void thread_ap_var_for_const7();
    void thread_ap_clk_no_reset_();
    void thread_addr_bram_address0();
    void thread_addr_bram_ce0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state22();
    void thread_ap_CS_fsm_state23();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_ap_sig_ioackin_gmem_ARREADY();
    void thread_ap_sig_ioackin_gmem_AWREADY();
    void thread_ap_sig_ioackin_gmem_WREADY();
    void thread_exitcond1_fu_263_p2();
    void thread_exitcond_fu_311_p2();
    void thread_gmem_ARADDR();
    void thread_gmem_ARVALID();
    void thread_gmem_AWADDR();
    void thread_gmem_AWVALID();
    void thread_gmem_BREADY();
    void thread_gmem_RREADY();
    void thread_gmem_WDATA();
    void thread_gmem_WVALID();
    void thread_gmem_blk_n_AR();
    void thread_gmem_blk_n_AW();
    void thread_gmem_blk_n_B();
    void thread_gmem_blk_n_R();
    void thread_gmem_blk_n_W();
    void thread_grp_load_fu_216_p1();
    void thread_hls_check();
    void thread_hls_check_ap_vld();
    void thread_i_1_cast2_fu_259_p1();
    void thread_i_2_cast1_fu_307_p1();
    void thread_i_3_fu_317_p2();
    void thread_i_fu_269_p2();
    void thread_j_1_fu_253_p2();
    void thread_j_cast_fu_244_p1();
    void thread_res_check_1_fu_360_p2();
    void thread_saMaster2_sum3_cast_fu_342_p1();
    void thread_saMaster2_sum3_fu_337_p2();
    void thread_saMaster2_sum_cast_fu_293_p1();
    void thread_saMaster2_sum_fu_288_p2();
    void thread_start_signal_o();
    void thread_start_signal_o_ap_vld();
    void thread_tmp_10_cast_fu_229_p1();
    void thread_tmp_1_fu_248_p2();
    void thread_tmp_2_fu_280_p2();
    void thread_tmp_4_fu_275_p1();
    void thread_tmp_5_cast_fu_284_p1();
    void thread_tmp_5_fu_219_p4();
    void thread_tmp_6_fu_352_p1();
    void thread_tmp_7_fu_355_p2();
    void thread_tmp_8_fu_323_p1();
    void thread_tmp_9_cast_fu_333_p1();
    void thread_tmp_fu_233_p2();
    void thread_tmp_s_fu_328_p2();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
