# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/zedboard_base_axi_smc_0.xci
# IP: The module: 'zedboard_base_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/bd_777a.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_10/bd_777a_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_16/bd_777a_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_22/bd_777a_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_17/bd_777a_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_18/bd_777a_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_19/bd_777a_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_20/bd_777a_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_21/bd_777a_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_11/bd_777a_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_12/bd_777a_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_13/bd_777a_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_14/bd_777a_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_15/bd_777a_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_7/bd_777a_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_8/bd_777a_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_9/bd_777a_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_2/bd_777a_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_3/bd_777a_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_4/bd_777a_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_5/bd_777a_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_6/bd_777a_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_0/bd_777a_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_1/bd_777a_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_base_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_10/bd_777a_s01a2s_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_16/bd_777a_m00s2a_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_17/bd_777a_m00arn_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_18/bd_777a_m00rn_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_19/bd_777a_m00awn_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_20/bd_777a_m00wn_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_21/bd_777a_m00bn_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_11/bd_777a_sarn_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_12/bd_777a_srn_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_13/bd_777a_sawn_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_14/bd_777a_swn_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_15/bd_777a_sbn_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_2/bd_777a_arsw_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_3/bd_777a_rsw_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_4/bd_777a_awsw_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_5/bd_777a_wsw_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_6/bd_777a_bsw_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_1/bd_777a_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_1/bd_777a_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/zedboard_base_axi_smc_0.xci
# IP: The module: 'zedboard_base_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/bd_777a.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_10/bd_777a_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_16/bd_777a_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_22/bd_777a_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_17/bd_777a_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_18/bd_777a_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_19/bd_777a_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_20/bd_777a_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_21/bd_777a_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_11/bd_777a_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_12/bd_777a_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_13/bd_777a_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_14/bd_777a_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_15/bd_777a_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_7/bd_777a_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_8/bd_777a_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_9/bd_777a_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_2/bd_777a_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_3/bd_777a_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_4/bd_777a_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_5/bd_777a_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_6/bd_777a_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_0/bd_777a_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_1/bd_777a_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_base_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_10/bd_777a_s01a2s_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_16/bd_777a_m00s2a_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_17/bd_777a_m00arn_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_18/bd_777a_m00rn_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_19/bd_777a_m00awn_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_20/bd_777a_m00wn_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_21/bd_777a_m00bn_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_11/bd_777a_sarn_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_12/bd_777a_srn_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_13/bd_777a_sawn_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_14/bd_777a_swn_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_15/bd_777a_sbn_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_2/bd_777a_arsw_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_3/bd_777a_rsw_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_4/bd_777a_awsw_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_5/bd_777a_wsw_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_6/bd_777a_bsw_0_ooc.xdc

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_1/bd_777a_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/tingyuan/Documents/zedboard-base-master/Vivado/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_0/bd_0/ip/ip_1/bd_777a_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.
