// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// BUS_A
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of start_signal_i
//        bit 31~0 - start_signal_i[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of start_signal_o
//        bit 31~0 - start_signal_o[31:0] (Read)
// 0x1c : Control signal of start_signal_o
//        bit 0  - start_signal_o_ap_vld (Read/COR)
//        others - reserved
// 0x20 : Data signal of hls_check
//        bit 31~0 - hls_check[31:0] (Read)
// 0x24 : Control signal of hls_check
//        bit 0  - hls_check_ap_vld (Read/COR)
//        others - reserved
// 0x28 : Data signal of num
//        bit 31~0 - num[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of saMaster
//        bit 31~0 - saMaster[31:0] (Read/Write)
// 0x34 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDDR_HLS_TEST_BUS_A_ADDR_AP_CTRL             0x00
#define XDDR_HLS_TEST_BUS_A_ADDR_GIE                 0x04
#define XDDR_HLS_TEST_BUS_A_ADDR_IER                 0x08
#define XDDR_HLS_TEST_BUS_A_ADDR_ISR                 0x0c
#define XDDR_HLS_TEST_BUS_A_ADDR_START_SIGNAL_I_DATA 0x10
#define XDDR_HLS_TEST_BUS_A_BITS_START_SIGNAL_I_DATA 32
#define XDDR_HLS_TEST_BUS_A_ADDR_START_SIGNAL_O_DATA 0x18
#define XDDR_HLS_TEST_BUS_A_BITS_START_SIGNAL_O_DATA 32
#define XDDR_HLS_TEST_BUS_A_ADDR_START_SIGNAL_O_CTRL 0x1c
#define XDDR_HLS_TEST_BUS_A_ADDR_HLS_CHECK_DATA      0x20
#define XDDR_HLS_TEST_BUS_A_BITS_HLS_CHECK_DATA      32
#define XDDR_HLS_TEST_BUS_A_ADDR_HLS_CHECK_CTRL      0x24
#define XDDR_HLS_TEST_BUS_A_ADDR_NUM_DATA            0x28
#define XDDR_HLS_TEST_BUS_A_BITS_NUM_DATA            32
#define XDDR_HLS_TEST_BUS_A_ADDR_SAMASTER_DATA       0x30
#define XDDR_HLS_TEST_BUS_A_BITS_SAMASTER_DATA       32

